# config.yaml

fragment_files_dir: '/home/ubuntu/mounted_vol/partitionning_module/datasets/watdiv100k'    # Directory containing fragment and common files
affectation_file: '/home/ubuntu/mounted_vol/partitionning_module/allocation/allocation_result/affectation_weighted_metis.txt'  # Path to the global affectation file
workers_file: '/home/ubuntu/mounted_vol/partitionning_module/workers'          # Path to the workers IP addresses file
master_ip_file: '/home/ubuntu/mounted_vol/partitionning_module/master'
temp_dir: '/home/ubuntu/mounted_vol/partitionning_module/temp'                    # Temporary directory for assembling files per worker
destination_path: '/home/ubuntu/mounted_vol/pqdag_temp_data'        # Destination path on both master and worker machines
storage_folder: '/home/ubuntu/mounted_vol/pqdag_data/watdiv100k' #where to store the permenant data
ssh_user: 'ubuntu'                               # SSH username for the workers
common_files:                                    # List of common files to send to all workers
  - 'spo_index.txt'
  - 'ops_index.txt'
  - 'predicates.txt'

