#!/usr/bin/python3
# Usage ./stop-worker qdag_instalation_folder

import sys, os
folder = sys.argv[1]
# Expand the user's home directory and set the working directory
working_directory = os.path.expanduser('~/pqdag')

# Ensure the working directory exists
if not os.path.isdir(working_directory):
    print(f"Working directory {working_directory} does not exist.")
    sys.exit(1)

# Change the working directory to ~/pqdag
os.chdir(working_directory)
os.system("kill $(cat worker.pid)")
