version: '3.9'

services:
  master:
    image: adpart-master:latest
    hostname: master
    volumes:
      - /home/ubuntu/mounted_vol:/data
    ports:
      - "2223:22"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == master
    networks:
      - adpart-network
  worker-1:
    image: adpart-worker:latest
    hostname: worker-1
    volumes:
      - /home/ubuntu/mounted_vol:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == worker-1
    networks:
      - adpart-network
  worker-2:
    image: adpart-worker:latest
    hostname: worker-2
    volumes:
      - /home/ubuntu/mounted_vol:/data
    deploy:
      replicas: 1    
      placement:
        constraints:
          - node.hostname == worker-2
    networks:
      - adpart-network

  worker-3:
    image: adpart-worker:latest
    hostname: worker-3
    volumes:
      - /home/ubuntu/mounted_vol:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == worker-3
    networks:
      - adpart-network

  worker-4:
    image: adpart-worker:latest
    hostname: worker-4
    volumes:
      - /home/ubuntu/mounted_vol:/data
    deploy:
      replicas: 1
      
        
          
        
          
      placement:
        constraints:
          - node.hostname == worker-4
    networks:
      - adpart-network
  worker-5:
    image: adpart-worker:latest
    hostname: worker-5
    volumes:
      - /home/ubuntu/mounted_vol:/data
    deploy:
      replicas: 1
      
        
          
        
          
      placement:
        constraints:
          - node.hostname == worker-5
    networks:
      - adpart-network
  worker-6:
    image: adpart-worker:latest
    hostname: worker-6
    volumes:
      - /home/ubuntu/mounted_vol:/data
    deploy:
      replicas: 1
      
        
          
        
          
      placement:
        constraints:
          - node.hostname == worker-6
    networks:
      - adpart-network
  worker-7:
    image: adpart-worker:latest
    hostname: worker-7
    volumes:
      - /home/ubuntu/mounted_vol:/data
    deploy:
      replicas: 1
      
        
          
        
          
      placement:
        constraints:
          - node.hostname == worker-7
    networks:
      - adpart-network
  worker-8:
    image: adpart-worker:latest
    hostname: worker-8
    volumes:
      - /home/ubuntu/mounted_vol:/data
    deploy:
      replicas: 1
      
        
          
        
          
      placement:
        constraints:
          - node.hostname == worker-8
    networks:
      - adpart-network
  worker-9:
    image: adpart-worker:latest
    hostname: worker-9
    volumes:
      - /home/ubuntu/mounted_vol:/data
    deploy:
      replicas: 1
      
        
          
        
          
      placement:
        constraints:
          - node.hostname == worker-9
    networks:
      - adpart-network
  worker-10:
    image: adpart-worker:latest
    hostname: worker-10
    volumes:
      - /home/ubuntu/mounted_vol:/data
    deploy:
      replicas: 1
      
        
          
        
          
      placement:
        constraints:
          - node.hostname == worker-10
    networks:
      - adpart-network
networks:
  adpart-network:
    driver: overlay
