version: "3.9"
services:
  master:
    hostname: adpart-master-1
    build: './build/'
    volumes:
      - ../data:/data/
    environment:
      - DISPLAY=host.docker.internal:0
  worker:
    build: './build/'
    deploy:
      mode: replicated
      replicas: 2
volumes:
  data: