version: '3.9'

services:
  master:
    image: sohad_master:latest
    hostname: master
    volumes:
      - /hdfs:/opt/hdfs/
      - /home/ubuntu/mounted_vol:/data
    ports:
      - "2222:22"
      - "50070:50070"
      - "8088:8088"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 25G # Limite la mémoire à 500 Mo
        reservations:
          memory: 25G # Réserve au moins 200 Mo de mémoire pour ce service
      placement:
        constraints:
          - node.hostname == master
    networks:
      - sohad-network

  worker-1:
    image: sohad_worker:latest
    hostname: worker-1
    volumes:
      - /home/ubuntu/mounted_vol:/opt/hdfs/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 25G # Limite la mémoire à 30 Go
        reservations:
          memory: 25G # Réserve au moins 28G de mémoire pour ce service
      placement:
        constraints:
          - node.hostname == worker-1
    networks:
      - sohad-network

  worker-2:
    image: sohad_worker:latest
    hostname: worker-2
    volumes:
      - /home/ubuntu/mounted_vol:/opt/hdfs/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 25G # Limite la mémoire à 30 Go
        reservations:
          memory: 25G # Réserve au moins 28G de mémoire pour ce service
      placement:
        constraints:
          - node.hostname == worker-2
    networks:
      - sohad-network

  worker-3:
    image: sohad_worker:latest
    hostname: worker-3
    volumes:
      - /home/ubuntu/mounted_vol:/opt/hdfs/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 25G # Limite la mémoire à 30 Go
        reservations:
          memory: 25G # Réserve au moins 28G de mémoire pour ce service
      placement:
        constraints:
          - node.hostname == worker-3
    networks:
      - sohad-network

  worker-4:
    image: sohad_worker:latest
    hostname: worker-4
    volumes:
      - /home/ubuntu/mounted_vol:/opt/hdfs/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 25G # Limite la mémoire à 30 Go
        reservations:
          memory: 25G # Réserve au moins 28G de mémoire pour ce service
      placement:
        constraints:
          - node.hostname == worker-4
    networks:
      - sohad-network
  worker-5:
    image: sohad_worker:latest
    hostname: worker-5
    volumes:
      - /home/ubuntu/mounted_vol:/opt/hdfs/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 25G # Limite la mémoire à 30 Go
        reservations:
          memory: 25G # Réserve au moins 28G de mémoire pour ce service
      placement:
        constraints:
          - node.hostname == worker-5
    networks:
      - sohad-network
  worker-6:
    image: sohad_worker:latest
    hostname: worker-6
    volumes:
      - /home/ubuntu/mounted_vol:/opt/hdfs/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 25G # Limite la mémoire à 30 Go
        reservations:
          memory: 25G # Réserve au moins 28G de mémoire pour ce service
      placement:
        constraints:
          - node.hostname == worker-6
    networks:
      - sohad-network
  worker-7:
    image: sohad_worker:latest
    hostname: worker-7
    volumes:
      - /home/ubuntu/mounted_vol:/opt/hdfs/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 25G # Limite la mémoire à 30 Go
        reservations:
          memory: 25G # Réserve au moins 28G de mémoire pour ce service
      placement:
        constraints:
          - node.hostname == worker-7
    networks:
      - sohad-network
  worker-8:
    image: sohad_worker:latest
    hostname: worker-8
    volumes:
      - /home/ubuntu/mounted_vol:/opt/hdfs/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 25G # Limite la mémoire à 30 Go
        reservations:
          memory: 25G # Réserve au moins 28G de mémoire pour ce service
      placement:
        constraints:
          - node.hostname == worker-8
    networks:
      - sohad-network
  worker-9:
    image: sohad_worker:latest
    hostname: worker-9
    volumes:
      - /home/ubuntu/mounted_vol:/opt/hdfs/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 25G # Limite la mémoire à 30 Go
        reservations:
          memory: 25G # Réserve au moins 28G de mémoire pour ce service
      placement:
        constraints:
          - node.hostname == worker-9
    networks:
      - sohad-network
  worker-10:
    image: sohad_worker:latest
    hostname: worker-10
    volumes:
      - /home/ubuntu/mounted_vol:/opt/hdfs/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 25G # Limite la mémoire à 30 Go
        reservations:
          memory: 25G # Réserve au moins 28G de mémoire pour ce service
      placement:
        constraints:
          - node.hostname == worker-10
    networks:
      - sohad-network
networks:
  sohad-network:
    driver: overlay

