version: '3.9'

services:
  master:
    image: sohad_master:latest
    hostname: master
    volumes:
      - /hdfs:/opt/hdfs/
      - /data:/data
    ports:
      - "2222:22"
      - "50070:50070"
      - "8088:8088"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 30G # Limite la mémoire à 500 Mo
        reservations:
          memory: 28G # Réserve au moins 200 Mo de mémoire pour ce service
      placement:
        constraints:
          - node.hostname == bench-master
    networks:
      - sohad-network

  worker01:
    image: sohad_worker:latest
    hostname: worker01
    volumes:
      - /hdfs:/opt/hdfs/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 30G # Limite la mémoire à 30 Go
        reservations:
          memory: 28G # Réserve au moins 28G de mémoire pour ce service
      placement:
        constraints:
          - node.hostname == worker01
    networks:
      - sohad-network

  worker02:
    image: sohad_worker:latest
    hostname: worker02
    volumes:
      - /hdfs:/opt/hdfs/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 30G # Limite la mémoire à 30 Go
        reservations:
          memory: 28G # Réserve au moins 28G de mémoire pour ce service
      placement:
        constraints:
          - node.hostname == worker02
    networks:
      - sohad-network

  worker03:
    image: sohad_worker:latest
    hostname: worker03
    volumes:
      - /hdfs:/opt/hdfs/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 30G # Limite la mémoire à 30 Go
        reservations:
          memory: 28G # Réserve au moins 28G de mémoire pour ce service
      placement:
        constraints:
          - node.hostname == worker03
    networks:
      - sohad-network

  worker04:
    image: sohad_worker:latest
    hostname: worker04
    volumes:
      - /hdfs:/opt/hdfs/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 30G # Limite la mémoire à 30 Go
        reservations:
          memory: 28G # Réserve au moins 28G de mémoire pour ce service
      placement:
        constraints:
          - node.hostname == worker04
    networks:
      - sohad-network

networks:
  sohad-network:
    driver: overlay
